import type React from 'react'

export const authStyles: Record<string, React.CSSProperties> = {
  root: {
    minHeight: '100vh',
    display: 'flex',
    backgroundColor: '#0d0d0d',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    color: '#f0ede8',
  },
  panel: {
    width: '380px',
    minWidth: '320px',
    maxWidth: '420px',
    margin: 'auto',
    padding: '48px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: '32px',
  },
  brand: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  brandMark: {
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    fontSize: '13px',
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    color: '#c8a96e',
    fontWeight: 500,
  },
  heading: {
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    fontSize: '28px',
    fontWeight: 700,
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    color: '#f0ede8',
    margin: 0,
  },
  sub: {
    fontSize: '14px',
    color: '#8a857d',
    marginTop: '4px',
  },
  divider: {
    borderTop: '1px solid #1e1e1e',
    margin: '0',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    fontSize: '11px',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#8a857d',
    fontWeight: 500,
  },
  input: {
    backgroundColor: '#181818',
    border: '1px solid #2a2a2a',
    borderRadius: '4px',
    padding: '11px 14px',
    fontSize: '15px',
    color: '#f0ede8',
    outline: 'none',
    transition: 'border-color 0.15s',
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    width: '100%',
    boxSizing: 'border-box',
  },
  inputFocus: {
    borderColor: '#c8a96e',
  },
  inputError: {
    borderColor: 'rgba(239, 68, 68, 0.6)',
  },
  hint: {
    fontSize: '11px',
    color: '#ef4444',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    marginTop: '2px',
  },
  error: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    border: '1px solid rgba(239, 68, 68, 0.3)',
    borderRadius: '4px',
    padding: '10px 14px',
    fontSize: '13px',
    color: '#ef4444',
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    letterSpacing: '0.01em',
  },
  submit: {
    backgroundColor: '#c8a96e',
    color: '#0d0d0d',
    border: 'none',
    borderRadius: '4px',
    padding: '13px 0',
    fontSize: '14px',
    fontWeight: 700,
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    marginTop: '4px',
    transition: 'background-color 0.15s, opacity 0.15s',
  },
  submitDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  footer: {
    fontSize: '13px',
    color: '#8a857d',
    textAlign: 'center',
  },
  link: {
    color: '#c8a96e',
    textDecoration: 'none',
    fontWeight: 600,
  },
}
